### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by matiasbastos**
Removed unused imports to fix build errors (fix https://github.com/sendinblue/APIv3-typescript-library/issues/25)

### CODE REVIEW

**Comment by matiasbastos** [comment]
Hi @aayush-sib , 
Can you please give a look to my PR? I'm about to go live with a SiB integration and will be nice to be able to use latest lib ;)

**Comment by aayush-sib** [comment]
Hi @matiasbastos 
Sorry for the delay, I was waiting for the other PR to get updated. Can you please create a branch from this project only and push changes to that branch instead of pushing it to the forked project?
Thanks!

**Comment by yurist38** [comment]
Hi guys! Any updates on this? What stops this PR from merging? @aayush-sib I don't really understand why you suggest creating a branch in this repo instead of merging the forked one... What is the difference?

**Comment by aayush-sib** [comment]
Hi @matiasbastos @yurist38 
I have released the wrapper with some changes. Can you please check it at your end if it's working fine?

Thanks, @matiasbastos for raising the PR, we appreciate your efforts. 

Regards
Sendinblue Team

**Comment by aayush-sib** [comment]
Hi @yurist38 
Can you please tell me the error you are getting?

**Comment by matiasbastos** [comment]
Sorry, I've been out for a while, this evening will retest. Thanks!

**Comment by yurist38** [comment]
@aayush-sib 
This is the error I see when I'm trying to build my Next.js project:

Screen Shot 2021-04-05 at 11 58 36

The error appears if I do import like this:

```
import { TransactionalEmailsApi } from 'sib-api-v3-typescript';
```

But when I require the library in this way:
```
const { TransactionalEmailsApi } = require('sib-api-v3-typescript');
```
then the error does not appear and the project builds successfully and works.

Right now I use `require()` but I'd like to use `import` instead...

**Comment by aayush-sib** [comment]
Hi @yurist38 
This error is something else than this. I am looking into it. This PR was mainly to remove unused imports.

**Comment by yurist38** [comment]
@aayush-sib Oh, you're right. Sorry, I've mixed up this PR with another one #23 . This is one that should fix it.

**Comment by aayush-sib** [comment]
Hi @yurist38 
Can you please share the configuration which you are using for building the project?
Thanks!

**Comment by matiasbastos** [comment]
Sorry, so what's missing here? Can this be merged?

**Comment by aayush-sib** [comment]
Hi @matiasbastos 

As you had already seen currently, we are using OpenAPI Generator to generate our typescript wrapper, we can't directly merge PR's since it's not recommended as we have to make all similar changes again when we will generate the wrapper. So, for this issue, I have introduced es lint in this wrapper which will remove all unused imports. I am still working on the other fix due to which the build is failing. 

Also, we are in planning to introduce our own custom-made wrappers and in those wrappers, other developers can also contribute.

**Comment by matiasbastos** [comment]
> Hi @matiasbastos
> 
> As you had already seen currently, we are using OpenAPI Generator to generate our typescript wrapper, we can't directly merge PR's since it's not recommended as we have to make all similar changes again when we will generate the wrapper. So, for this issue, I have introduced es lint in this wrapper which will remove all unused imports. I am still working on the other fix due to which the build is failing.
> 
> Also, we are in planning to introduce our own custom-made wrappers and in those wrappers, other developers can also contribute.

That sounds great! So guess it's ok to close this PR as is going to be fixed in a future release?

**Comment by aayush-sib** [comment]
>So guess it's ok to close this PR

I haven't closed this PR because I was waiting for your response, whether this issue (unused imports issue) is fixed or not. If this issue is fixed you can close this PR 🙂 .

**Pull request closed without merging**
